export const TAJWEED_RULES = [
  {
    id: 'ghunnah',
    name: 'Ghunnah',
    arabic: 'غُنَّة',
    colorKey: 'ghunnah',
    explanation: 'A nasalized sound held for about two counts. It appears most clearly on noon and meem with shaddah.',
    example: 'إِنَّ',
    note: 'The noon mushaddad is held nasally.',
    verseKey: '98:5',
    wordPosition: 3,
  },
  {
    id: 'ikhfa',
    name: 'Ikhfa',
    arabic: 'إخفاء',
    colorKey: 'ikhfa',
    explanation: 'The noon sakinah or tanween is softened and partly hidden before fifteen letters, with a light nasal quality.',
    example: 'مِنْ شَرِّ',
    note: 'The noon sound is concealed before sheen.',
    verseKey: '113:2',
    wordPosition: 1,
  },
  {
    id: 'idgham',
    name: 'Idgham',
    arabic: 'إدغام',
    colorKey: 'idgham',
    explanation: 'One letter merges into the next. Some forms keep ghunnah, and others merge cleanly without nasalization.',
    example: 'مِنْ وَالٍ',
    note: 'Noon merges into waw.',
    verseKey: '13:11',
    wordPosition: 5,
  },
  {
    id: 'iqlab',
    name: 'Iqlab',
    arabic: 'إقلاب',
    colorKey: 'iqlab',
    explanation: 'The noon sakinah or tanween changes into a hidden meem before the letter ba.',
    example: 'أَنْبِئْهُمْ',
    note: 'The noon changes to a concealed meem before ba.',
    verseKey: '2:33',
    wordPosition: 1,
  },
  {
    id: 'madd',
    name: 'Madd',
    arabic: 'مد',
    colorKey: 'madd',
    explanation: 'An elongation in the vowel sound. Different types are stretched for different counts depending on what follows.',
    example: 'الضَّالِّينَ',
    note: 'The long vowel is stretched clearly.',
    verseKey: '1:7',
    wordPosition: 8,
  },
  {
    id: 'qalqalah',
    name: 'Qalqalah',
    arabic: 'قلقلة',
    colorKey: 'qalqalah',
    explanation: 'A light echo on the letters ق ط ب ج د when they carry sukoon, especially when stopping on them.',
    example: 'أَحَدٌ',
    note: 'The dal echoes when stopping.',
    verseKey: '112:1',
    wordPosition: 3,
  },
  {
    id: 'ikhfaShafawi',
    name: 'Ikhfa Shafawi',
    arabic: 'إخفاء شفوي',
    colorKey: 'ikhfaShafawi',
    explanation: 'A hidden meem sakinah before ba, read with a soft lip closure and ghunnah.',
    example: 'تَرْمِيهِمْ بِحِجَارَةٍ',
    note: 'The meem is lightly concealed before ba.',
    verseKey: '105:4',
    wordPosition: 1,
  },
  {
    id: 'idghamShafawi',
    name: 'Idgham Shafawi',
    arabic: 'إدغام شفوي',
    colorKey: 'idghamShafawi',
    explanation: 'A meem sakinah merges into another meem with ghunnah and a gentle lip hold.',
    example: 'لَهُمْ مَغْفِرَةٌ',
    note: 'The first meem merges into the second meem.',
    verseKey: '2:5',
    wordPosition: 2,
  },
  {
    id: 'heavyLight',
    name: 'Heavy & Light Letters',
    arabic: 'تفخيم وترقيق',
    colorKey: 'izhar',
    explanation: 'Some letters are always heavy, most are light, and a few switch based on context such as ra, lam, and the lafz al-jalalah.',
    example: 'الصِّرَاطَ',
    note: 'The sad is pronounced with heaviness.',
    verseKey: '1:6',
    wordPosition: 2,
  },
];

export const PRACTICE_SURAHS = [
  { id: 1, name: 'Al-Fatihah', arabic: 'الفاتحة', ayahs: 7 },
  { id: 93, name: 'Ad-Duhaa', arabic: 'الضحى', ayahs: 11 },
  { id: 94, name: 'Ash-Sharh', arabic: 'الشرح', ayahs: 8 },
  { id: 95, name: 'At-Tin', arabic: 'التين', ayahs: 8 },
  { id: 96, name: 'Al-\'Alaq', arabic: 'العلق', ayahs: 19 },
  { id: 97, name: 'Al-Qadr', arabic: 'القدر', ayahs: 5 },
  { id: 98, name: 'Al-Bayyinah', arabic: 'البينة', ayahs: 8 },
  { id: 99, name: 'Az-Zalzalah', arabic: 'الزلزلة', ayahs: 8 },
  { id: 100, name: 'Al-\'Adiyat', arabic: 'العاديات', ayahs: 11 },
  { id: 101, name: 'Al-Qari\'ah', arabic: 'القارعة', ayahs: 11 },
  { id: 102, name: 'At-Takathur', arabic: 'التكاثر', ayahs: 8 },
  { id: 103, name: 'Al-\'Asr', arabic: 'العصر', ayahs: 3 },
  { id: 104, name: 'Al-Humazah', arabic: 'الهمزة', ayahs: 9 },
  { id: 105, name: 'Al-Fil', arabic: 'الفيل', ayahs: 5 },
  { id: 106, name: 'Quraysh', arabic: 'قريش', ayahs: 4 },
  { id: 107, name: 'Al-Ma\'un', arabic: 'الماعون', ayahs: 7 },
  { id: 108, name: 'Al-Kawthar', arabic: 'الكوثر', ayahs: 3 },
  { id: 109, name: 'Al-Kafirun', arabic: 'الكافرون', ayahs: 6 },
  { id: 110, name: 'An-Nasr', arabic: 'النصر', ayahs: 3 },
  { id: 111, name: 'Al-Masad', arabic: 'المسد', ayahs: 5 },
  { id: 112, name: 'Al-Ikhlas', arabic: 'الإخلاص', ayahs: 4 },
  { id: 113, name: 'Al-Falaq', arabic: 'الفلق', ayahs: 5 },
  { id: 114, name: 'An-Nas', arabic: 'الناس', ayahs: 6 },
];
